### ISSUE TITLE
Missing `github.com/kubernetes-client/ruby-base` repository

### ISSUE THREAD

**Issue by yuanying** [kubernetes-client/ruby#2]
I've read the [proposal document](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/csi-client-structure-proposal.md) about client library structure.
But I can't find core library for ruby.

I'm interested in this repository, so is there anything I can do?

**Comment by mbohlool** [comment]
This client is in very early stages of development and need people to contribute to. If you are interested in contributing, I will layout some tasks in form of issues here, so please pick one and let me know if you need any help with it.

**Comment by yuanying** [comment]
Thanks for your comment! I'll work as soon as possible.
