### ISSUE TITLE
Support kubeconfig loader

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-client/ruby#3]
Just like python client [here](https://github.com/kubernetes-client/python-base/blob/a41c44715241552de73361673152f3f0d0bb9bc4/config/incluster_config.py) and [here](https://github.com/kubernetes-client/python-base/blob/a41c44715241552de73361673152f3f0d0bb9bc4/config/kube_config.py), we need to support loading kubeconfig both in cluster and outside of the cluster.

**Comment by yuanying** [comment]
This repository seems `core-ruby`, so I think, supporting kubeconfig loader should be included `ruby-base` repository. 
Or is it better to implement this for now, and split later?

**Comment by yuanying** [comment]
I've checked other clients (java, javascript) and I found these have base functionality inside itself. So I'll fix this issue to this repository too.

**Comment by mbohlool** [comment]
Yeah, we can develop here for now and when we got a stable version, we can split.

**Comment by mbohlool** [comment]
fixed by #8
