### ISSUE TITLE
Support Watch

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-client/ruby#4]
Watch is a non-standard method that swagger-codegen does not support and we need to add support for it like other clients (e.g. python [here](https://github.com/kubernetes-client/python-base/tree/a41c44715241552de73361673152f3f0d0bb9bc4/watch))

**Comment by yuanying** [comment]
Memo: To support this, `swagger-codegen` is also needed to be modified like https://github.com/swagger-api/swagger-codegen/pull/4166 .
