### ISSUE TITLE
Support exec/attach calls

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-client/ruby#5]
Exec and Attach class are non-standard calls that kubernetes API server uses to connect to a port of a pod/container or execute a command on them. It uses SPDY or WebSockets. Normal calls to these endpoints will result in an upgrade request from API server. We need to support WebSocket for this client (for those endpoints). [This is python](https://github.com/kubernetes-client/python-base/tree/a41c44715241552de73361673152f3f0d0bb9bc4/stream) implementation of the same feature.

**Comment by zhongxiao37** [comment]
Could we reopen this issue? This issue is not resolved yet.

The code in document doesn't work and error message returns

```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Upgrade request required","reason":"BadRequest","code":400}
```
