### ISSUE TITLE
 undefined method `encode' for URI:Module with Ruby 3

### ISSUE THREAD

**Issue by gingermusketeer** [kubernetes-client/ruby#56]
Ruby 3 removed the deprecated `encode` method from the URI module. The usage at https://github.com/kubernetes-client/ruby/blob/33861097e2eab9954b3f07f6898e5e8199199731/kubernetes/lib/kubernetes/api_client.rb#L267 is causing the gem to break as a result.

**Comment by jakeonfire** [comment]
more generally, does this library have a future or have the community-owned libraries taken precedence?
